[package]
name = "mzworker-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
duckdb = { version = "~1.10505.0", features = ["parquet"] }
tonic = "0.12"
prost = "0.13"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
sqlparser = "0.52"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
tonic-build = "0.12"
